version: "3.9"
services:
  libreria:
    build: .
    volumes:
      - .:/django
    container_name: libreria-django
    ports: 
    - "8000:8000"
    image: app/django
    depends_on:
      - db
  db:
    image: postgres
    ports: 
    - "5432:5432"